# CMake generated Testfile for 
# Source directory: /Users/lucasgoudin/dev/encre/.claude/worktrees/github-release-ci-workflow-e86e00
# Build directory: /Users/lucasgoudin/dev/encre/.claude/worktrees/github-release-ci-workflow-e86e00/build-asan
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test("unit" "/Users/lucasgoudin/dev/encre/.claude/worktrees/github-release-ci-workflow-e86e00/build-asan/unit_tests")
set_tests_properties("unit" PROPERTIES  _BACKTRACE_TRIPLES "/Users/lucasgoudin/dev/encre/.claude/worktrees/github-release-ci-workflow-e86e00/CMakeLists.txt;59;add_test;/Users/lucasgoudin/dev/encre/.claude/worktrees/github-release-ci-workflow-e86e00/CMakeLists.txt;0;")
add_test("sim_home" "/Users/lucasgoudin/dev/encre/.claude/worktrees/github-release-ci-workflow-e86e00/build-asan/reader_sim" "home" "/Users/lucasgoudin/dev/encre/.claude/worktrees/github-release-ci-workflow-e86e00/build-asan/sim_home.png")
set_tests_properties("sim_home" PROPERTIES  _BACKTRACE_TRIPLES "/Users/lucasgoudin/dev/encre/.claude/worktrees/github-release-ci-workflow-e86e00/CMakeLists.txt;103;add_test;/Users/lucasgoudin/dev/encre/.claude/worktrees/github-release-ci-workflow-e86e00/CMakeLists.txt;0;")
add_test("sim_app" "/Users/lucasgoudin/dev/encre/.claude/worktrees/github-release-ci-workflow-e86e00/build-asan/reader_sim" "app" "/Users/lucasgoudin/dev/encre/.claude/worktrees/github-release-ci-workflow-e86e00/build-asan/sim_app.png" "--keys" "DOWN,DOWN,CONFIRM,CONFIRM,CONFIRM+")
set_tests_properties("sim_app" PROPERTIES  _BACKTRACE_TRIPLES "/Users/lucasgoudin/dev/encre/.claude/worktrees/github-release-ci-workflow-e86e00/CMakeLists.txt;107;add_test;/Users/lucasgoudin/dev/encre/.claude/worktrees/github-release-ci-workflow-e86e00/CMakeLists.txt;0;")
add_test("sim_library" "/Users/lucasgoudin/dev/encre/.claude/worktrees/github-release-ci-workflow-e86e00/build-asan/reader_sim" "library" "/Users/lucasgoudin/dev/encre/.claude/worktrees/github-release-ci-workflow-e86e00/build-asan/sim_library.png" "--canvas" "528x792")
set_tests_properties("sim_library" PROPERTIES  _BACKTRACE_TRIPLES "/Users/lucasgoudin/dev/encre/.claude/worktrees/github-release-ci-workflow-e86e00/CMakeLists.txt;112;add_test;/Users/lucasgoudin/dev/encre/.claude/worktrees/github-release-ci-workflow-e86e00/CMakeLists.txt;0;")
add_test("sim_library_actions" "/Users/lucasgoudin/dev/encre/.claude/worktrees/github-release-ci-workflow-e86e00/build-asan/reader_sim" "library_actions" "/Users/lucasgoudin/dev/encre/.claude/worktrees/github-release-ci-workflow-e86e00/build-asan/sim_library_actions.png" "--canvas" "528x792")
set_tests_properties("sim_library_actions" PROPERTIES  _BACKTRACE_TRIPLES "/Users/lucasgoudin/dev/encre/.claude/worktrees/github-release-ci-workflow-e86e00/CMakeLists.txt;116;add_test;/Users/lucasgoudin/dev/encre/.claude/worktrees/github-release-ci-workflow-e86e00/CMakeLists.txt;0;")
add_test("sim_delete_confirm" "/Users/lucasgoudin/dev/encre/.claude/worktrees/github-release-ci-workflow-e86e00/build-asan/reader_sim" "delete_confirm" "/Users/lucasgoudin/dev/encre/.claude/worktrees/github-release-ci-workflow-e86e00/build-asan/sim_delete_confirm.png" "--canvas" "480x800")
set_tests_properties("sim_delete_confirm" PROPERTIES  _BACKTRACE_TRIPLES "/Users/lucasgoudin/dev/encre/.claude/worktrees/github-release-ci-workflow-e86e00/CMakeLists.txt;120;add_test;/Users/lucasgoudin/dev/encre/.claude/worktrees/github-release-ci-workflow-e86e00/CMakeLists.txt;0;")
add_test("sim_book_details" "/Users/lucasgoudin/dev/encre/.claude/worktrees/github-release-ci-workflow-e86e00/build-asan/reader_sim" "book_details" "/Users/lucasgoudin/dev/encre/.claude/worktrees/github-release-ci-workflow-e86e00/build-asan/sim_book_details.png" "--canvas" "480x800")
set_tests_properties("sim_book_details" PROPERTIES  _BACKTRACE_TRIPLES "/Users/lucasgoudin/dev/encre/.claude/worktrees/github-release-ci-workflow-e86e00/CMakeLists.txt;124;add_test;/Users/lucasgoudin/dev/encre/.claude/worktrees/github-release-ci-workflow-e86e00/CMakeLists.txt;0;")
add_test("sim_typography" "/Users/lucasgoudin/dev/encre/.claude/worktrees/github-release-ci-workflow-e86e00/build-asan/reader_sim" "typography" "/Users/lucasgoudin/dev/encre/.claude/worktrees/github-release-ci-workflow-e86e00/build-asan/sim_typography.png" "--canvas" "528x792")
set_tests_properties("sim_typography" PROPERTIES  _BACKTRACE_TRIPLES "/Users/lucasgoudin/dev/encre/.claude/worktrees/github-release-ci-workflow-e86e00/CMakeLists.txt;132;add_test;/Users/lucasgoudin/dev/encre/.claude/worktrees/github-release-ci-workflow-e86e00/CMakeLists.txt;0;")
add_test("sim_sd_missing" "/Users/lucasgoudin/dev/encre/.claude/worktrees/github-release-ci-workflow-e86e00/build-asan/reader_sim" "sd_missing" "/Users/lucasgoudin/dev/encre/.claude/worktrees/github-release-ci-workflow-e86e00/build-asan/sim_sd_missing.png")
set_tests_properties("sim_sd_missing" PROPERTIES  _BACKTRACE_TRIPLES "/Users/lucasgoudin/dev/encre/.claude/worktrees/github-release-ci-workflow-e86e00/CMakeLists.txt;135;add_test;/Users/lucasgoudin/dev/encre/.claude/worktrees/github-release-ci-workflow-e86e00/CMakeLists.txt;0;")
add_test("sim_storage" "/Users/lucasgoudin/dev/encre/.claude/worktrees/github-release-ci-workflow-e86e00/build-asan/reader_sim" "sd_missing" "/Users/lucasgoudin/dev/encre/.claude/worktrees/github-release-ci-workflow-e86e00/build-asan/sim_storage.png" "--root" "/Users/lucasgoudin/dev/encre/.claude/worktrees/github-release-ci-workflow-e86e00/build-asan")
set_tests_properties("sim_storage" PROPERTIES  _BACKTRACE_TRIPLES "/Users/lucasgoudin/dev/encre/.claude/worktrees/github-release-ci-workflow-e86e00/CMakeLists.txt;139;add_test;/Users/lucasgoudin/dev/encre/.claude/worktrees/github-release-ci-workflow-e86e00/CMakeLists.txt;0;")
