#pragma once

// THE TYPE RAMP'S ROLE-TO-ASSET BINDING, stated once.
//
// Three loaders bind the same eleven roles to the same eleven assets in three
// build worlds -- the shell's embedded arrays (kFont<Role> / kFont<Role>Size,
// generated by tools/embed_font.py with names that match the Role enum), the
// simulator's file loads, and the unit tests' ramp.h -- and before this each
// spelled the list out by hand, so adding a role meant editing the same eleven
// lines three times in lockstep. FontSet::ready() still catches a role nothing
// loaded, and FontSet::load still refuses an asset built at the wrong ppem or
// weight; what the manifest adds is that "the same eleven, bound the same way"
// is one claim instead of three.
//
// Each entry is X(Role, asset-stem): the stem is the built asset's basename,
// `<stem>.rfnt` under assets/built/, and the embedded header generated from it.
// The stems encode the pt sizes CLAUDE.md's Type table states (ppem = pt * 150
// / 72), and FontSet::load is what checks the binding at run time -- a stem
// edited here to the wrong size fails the boot rather than drawing a screen in
// the wrong face.
//
// The body face (kFontBodySerif) is deliberately NOT here: it is
// ScalableFont's, rasterised at runtime, not a pre-rendered ramp asset.
#define READER_FONT_RAMP(X)             \
  X(Meta400, spacegrotesk_400_10pt)     \
  X(Meta500, spacegrotesk_500_10pt)     \
  X(Label400, spacegrotesk_400_11pt)    \
  X(Label500, spacegrotesk_500_11pt)    \
  X(Value500, spacegrotesk_500_12pt)    \
  X(Value700, spacegrotesk_700_12pt)    \
  X(Body400, spacegrotesk_400_14pt)     \
  X(Body500, spacegrotesk_500_14pt)     \
  X(Body700, spacegrotesk_700_14pt)     \
  X(Title700, spacegrotesk_700_20pt)    \
  X(Display700, spacegrotesk_700_32pt)
