#!/usr/bin/env python3
"""Generate the named-entity table for Xml::decodeEntity, as a C++ header.

Why a generator: the same reason mkzip.py and iconc.py are generators. 252 names
typed by hand is 252 chances to transpose a code point, and the authority is already
on the machine -- Python's `html.entities.name2codepoint` IS the HTML 4.01 list.

Why HTML 4's 252 and not HTML 5's 2,125: the longest HTML 4 name is 8 bytes, which
fits xml.cpp's existing 16-byte entity scratch with room to spare, and the measured
need is seven names -- rsquo, nbsp, mdash, ndash, ldquo, rdquo, lsquo, which is every
distinct named entity across sixteen real books. The passthrough in decodeEntity is
what makes that a safe choice rather than a bet: an entity outside this table costs
its own five characters of ugliness, never a chapter.

Usage:
    python3 tools/entities.py --out core/src/entity_table.h
"""

import argparse
from html.entities import name2codepoint


def emit(out_path):
    rows = sorted(name2codepoint.items())
    longest = max(len(n) for n, _ in rows)
    lines = [
        "#pragma once",
        "// GENERATED by tools/entities.py -- do not edit.",
        "//",
        "// HTML 4.01's named character references, sorted by name so decodeEntity can",
        "// binary-search them. An entity NOT in here is passed through as its own text,",
        "// which is why this table being incomplete can never cost a chapter.",
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "namespace reader {",
        "",
        "struct NamedEntity {",
        "  const char* name;",
        "  uint32_t cp;",
        "};",
        "",
        "// The longest name here is %d bytes, which is why xml.cpp's 16-byte entity" % longest,
        "// scratch is enough to hold any of them.",
        "inline constexpr NamedEntity kNamedEntities[] = {",
    ]
    for name, cp in rows:
        lines.append('    {"%s", 0x%04X},' % (name, cp))
    lines += [
        "};",
        "",
        "inline constexpr size_t kNamedEntityCount =",
        "    sizeof(kNamedEntities) / sizeof(kNamedEntities[0]);",
        "",
        "}  // namespace reader",
        "",
    ]
    with open(out_path, "w") as fh:
        fh.write("\n".join(lines))
    print("%s: %d entities, longest name %d bytes" % (out_path, len(rows), longest))


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", required=True, help="the entity table header")
    emit(ap.parse_args().out)


if __name__ == "__main__":
    main()
