#!/usr/bin/env python3
"""iconc: design-board SVG -> 2-bit anti-aliased icon bitmaps in a C++ header.

Usage: python3 tools/iconc.py --out core/src/icons_data.h
       python3 tools/iconc.py --out core/src/icons_data.h --sheet build/icons.png

The firmware's UI marks used to be hand-authored binary literals. They were
drawn from a *description* of the design's icons rather than from the icons
themselves, and drifted twice: once in shape (the book read as the letters
"OC") and once in size (the chrome type ramp doubled to pt-at-150dpi and the
boards' icons grew with it, while the bitmaps stayed at 13x13). This tool ends
both failure modes the way tools/fontc.py ended them for type: the bytes are
generated from the design's own source, so they cannot disagree with it.

Pipeline, per icon:
  1. The named design board is read and its `<svg>` elements are scanned for the
     one containing this icon's `match` string. That element -- opening tag,
     width, height, viewBox and all its children -- is taken verbatim. Nothing
     about the geometry or the size is stored in this tool, so a change on a
     board propagates on the next `make icons` and cannot be missed.
  2. Headless Chrome rasterises it on an opaque white ground. Chrome is the only
     SVG rasteriser on this machine (no cairosvg/rsvg/inkscape) and it is the
     same renderer tools/compare-design.py measures the design with, so an icon
     is compared against the engine that drew the reference.
  3. Ink coverage (255 - luma) is quantised to 2 bits, 0..3, with fontc.py's
     rounding, and packed MSB-first four pixels per byte.

This tool used to hold *copies* of the boards' path data and rendered sizes.
That is the same failure mode one level up: a design change to an arrow's
geometry, or to a hint bar's mark sizes, regenerated byte-identical output
because the generator was reading its own stale transcript rather than the
design. The mapping kept below is deliberately the minimum that cannot go stale
on its own: name -> (board, a distinctive substring to locate the icon by). If
that substring stops matching exactly one `<svg>` the tool refuses to emit
anything, because a generator that silently picks a different icon is worse than
one that fails.

2 bits, not 1: these are stroke icons at 21-46px with curves, diagonals and
~2px stems. Thresholding them reproduces exactly the staircase that made the
1-bit chrome type illegible on the panel. Icon::coverage/drawIcon in
core/src/icons.cpp unpack this layout, and reader::Plane splits it into the
panel's two grey planes just as glyphs are split.

Do not edit the emitted header; edit the definitions below and rerun `make
icons`.
"""
import argparse
import os
import pathlib
import re
import subprocess
import sys
import tempfile

try:
    from PIL import Image
except ImportError:  # pragma: no cover - tool-only dependency
    sys.exit("error: Pillow is required (pip install -r tools/requirements.txt)")

CHROME = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"

# The curated icon set. Two fields carry design data and neither is design data
# itself: `source` names the board that owns the icon, and `match` is a substring
# that appears in exactly one `<svg>` on that board. Everything the generator
# actually rasterises -- geometry, viewBox, width, height -- is read out of the
# board at generation time.
#
# Choosing a `match`: prefer the part of the mark that identifies *which* mark it
# is over the part a designer is likely to retune. `M8 13V3` says "the up arrow"
# and would survive a stroke-width change; `stroke-width="1.6"` says nothing and
# matches three other icons. Where a mark has no path data to key on (the dot,
# the battery) an element or a distinctive attribute serves the same purpose.
ICONS = {
    "back": {
        "symbol": "kBack",
        "note": "arrow curving left: the Back button",
        "source": "design/Library.dc.html",
        "match": "M6 4L2 8l4 4",
    },
    # kBack's counterpart, and the only mark in the set that is not a hint-bar
    # button: it is the disclosure on an action block (Main's CONTINUE, and every
    # primary action on the flow boards). A long arrow with a shaft, 32x25 --
    # deliberately not the 25x25 chevron a menu row uses, which the firmware drew
    # here for want of this icon. The board authors it in white for the inverted
    # block; extract() re-colours it, since colour is Ink's business, not an
    # icon's.
    "forward": {
        "symbol": "kForward",
        "note": "long arrow: an action block's proceed mark",
        "source": "design/Main.dc.html",
        "match": "M1 7h15M11 1l6 6-6 6",
    },
    "dot": {
        "symbol": "kDot",
        "note": "filled circle: the Confirm button",
        "source": "design/Main.dc.html",
        "match": "<circle",
    },
    # The hollow twin of the dot, and the one mark that is not a button: it sits
    # *after* a hint's label to say that button has a long-press action. It shares
    # the dot's geometry exactly (`cx=5 cy=5 r=3.2` on a 0 0 10 10 viewBox) and
    # differs only in being stroked rather than filled -- so `<circle`, which is
    # all the dot needs on its own board, would match both here. The match keys on
    # the difference that identifies it: the dot's radius, drawn hollow. That
    # survives a stroke-width retune, and `stroke-width="1"` would not identify it
    # at all.
    "hold": {
        "symbol": "kHold",
        "note": "hollow ring: this button has a long-press action",
        "source": "design/Library.dc.html",
        "match": 'r="3.2" fill="none"',
    },
    "up": {
        "symbol": "kUp",
        "note": "stem with a chevron head, pointing up",
        "source": "design/Main.dc.html",
        "match": "M8 13V3",
    },
    "down": {
        "symbol": "kDown",
        "note": "stem with a chevron head, pointing down",
        "source": "design/Main.dc.html",
        "match": "M8 3v10",
    },
    "chevron": {
        "symbol": "kChevron",
        "note": "right-pointing disclosure",
        "source": "design/Main.dc.html",
        "match": "M6 3l5 5-5 5",
    },
    "book": {
        "symbol": "kBook",
        "note": "open book: the Read action",
        "source": "design/Main.dc.html",
        "match": "M8 3.2C6.6 2",
    },
    # The SAME path at a different size, which is why it is a second entry rather
    # than a second use of kBook: these are pre-rendered bitmaps, so a 112px mark
    # and a 25px one are two assets. The matcher keys on path data, and both boards
    # carry this path -- so `source` is what disambiguates them, and it has to.
    "book_large": {
        "symbol": "kBookLarge",
        "note": "the empty-library mark, 112px on HomeEmpty",
        "source": "design/HomeEmpty.dc.html",
        "match": "M8 3.2C6.6 2",
    },
    "folder": {
        "symbol": "kFolder",
        "note": "folder: a Library directory row",
        "source": "design/Library.dc.html",
        "match": "M1 4a2 2 0 0 1 2-2h6l3 3h11",
    },
    "battery": {
        "symbol": "kBattery",
        "note": "the header band's charge cell",
        "source": "design/Main.dc.html",
        "match": '<rect x="19.5"',
    },
    # THE SAME MARK WITH A BOLT KNOCKED OUT, and a second entry rather than a
    # variant for the reason book_large is one: these are pre-rendered bitmaps,
    # so two states are two assets. The match keys on the bolt's own path,
    # because that is the part that says WHICH mark this is -- the terminal nub
    # (`<rect x="19.5"`) is on BOTH batteries and identifies neither, the same
    # shortcut sdcard and hold both carry comments rejecting. `source` is then a
    # second line of defence (it has to be a board holding exactly one battery),
    # not the only one. The fallback the board documents -- dropping the fill
    # and making the bolt black instead of white -- changes `fill`, not `d`, so
    # this match survives it.
    "battery_charging": {
        "symbol": "kBatteryCharging",
        "note": "the header band's charge cell, bolt knocked out: charging",
        "source": "design/HomeCharging.dc.html",
        "match": "M11.4 2",
    },
    # A SECOND ASSET FOR THE SAME DRAWING, at 98x52 against kBattery's 38x21 --
    # these are pre-rendered bitmaps and there is no scaling one up. kBookLarge's
    # precedent exactly, and it is a second *state* as well as a second size: the
    # fill bar is 2.5 units wide where the header band's is 14.
    #
    # `source` HAS TO DISAMBIGUATE IT, AND IS THE ONLY THING THAT DOES. Every
    # element of this mark is on Main.dc.html's battery too -- the body rect, the
    # terminal nub kBattery keys on, and this `rect x="2" y="2"`, which differs
    # only in its `width`. So the match locates the mark on its own board and the
    # board name is the primary key, exactly as for kBook/kBookLarge. Keying on
    # `width="2.5"` would distinguish them and is worse: how empty "empty" looks
    # is the part of this mark a designer would retune.
    "battery_large": {
        "symbol": "kBatteryLarge",
        "note": "a nearly-empty battery drawn large: the critical-shutdown mark",
        "source": "design/BatteryEmpty.dc.html",
        "match": 'rect x="2" y="2"',
    },
    # The only mark in the set that is neither a button nor a row ornament: it is
    # the subject of a full-screen prompt, drawn at 84x105 where every other mark
    # here is 21-46px. The match keys on the card's own outline -- the notched
    # body -- rather than on the three contact rects, which are three
    # indistinguishable `<rect>`s and would not identify the mark if the outline
    # were ever retuned.
    "sdcard": {
        "symbol": "kSdCard",
        "note": "an SD card, notched corner and contacts: the no-card prompt",
        "source": "design/SdMissing.dc.html",
        "match": "M4 1h9l6 6v16",
    },
    # The other mark that is neither a button nor a row ornament, alongside
    # sdcard: the end-of-book confirmation tick, 26x21 on its board. The match
    # keys on the tick's own two-segment path, which no hint-bar mark carries.
    # THE SAME PATH IS ON TWO OTHER BOARDS -- SyncDone at 26x21 and WebUpload at
    # 15x12, both parked V2 Wi-Fi screens -- so `source` is what disambiguates
    # them, exactly as it does for book/book_large, and it has to.
    #
    # IT IS A THIN DIAGONAL, which is the shape Plane::Bw treats worst --
    # kChevron's stroke is mostly coverage-1 pixels and comes out a notch
    # lighter. At 26x21 the stroke resolves thicker than the chevron's, so it
    # should hold, but that is an argument and only the panel can settle it.
    "check": {
        "symbol": "kCheck",
        "note": "a tick: the end-of-book confirmation mark",
        "source": "design/BookEnd.dc.html",
        "match": "M1 6l5 5L15 1",
    },
    # THE WARNING TRIANGLE, 32x28, and THREE BOARDS DRAW IT -- BookError.dc.html,
    # BookErrorUnreadable.dc.html and LowBattery.dc.html. It arrived twice, on two
    # branches at once (the corrupt-book dialog and the low-battery banner), each
    # adding a `warning` entry naming its own board. ICONS is a DICT, so keeping
    # both would have let the second silently overwrite the first rather than
    # failing -- one entry is the resolution, not a merge of two.
    #
    # ONE BITMAP SERVES ALL THREE, and that is a fact about the generator rather
    # than a coincidence: the three svgs are geometrically identical -- same
    # viewBox, same three shapes, same 1.6 stroke -- and differ only in COLOUR,
    # #000000 on the two dialogs against #ffffff on the banner, which draws it
    # inside an inverted band. extract() re-colours an all-white mark to black
    # because the bitmap is coverage and reader::Ink picks the colour at draw
    # time, so the white authoring rasterises to the same bytes. The banner's
    # board is honest about the ink it is drawn in; it is not a second mark.
    #
    # `source` NAMES BookError.dc.html AND THE CHOICE IS ARBITRARY between the
    # three -- the match `M9 1 17 15H1z` is on all of them, so `source` is the
    # second line of defence kBook/kBookLarge and kBattery/kBatteryCharging need,
    # not a statement that this board owns the design. The cost is the one shared
    # icons always have: editing the triangle on LowBattery.dc.html alone would
    # not reach the generator. Change it on all three or on none.
    #
    # THREE DIAGONALS, which is the shape Mono thresholding treats worst:
    # CLAUDE.md records kChevron coming out a notch lighter because its stroke is
    # mostly coverage-1 pixels. At 32x28 with a 1.6 stroke this should hold, but
    # that is an argument and only the panel can settle it.
    "warning": {
        "symbol": "kWarning",
        "note": "a warning triangle: the corrupt-book dialog and low-battery mark",
        "source": "design/BookError.dc.html",
        "match": "M9 1 17 15H1z",
    },
}

# The boards are hand-written one-element-per-line HTML with no nested <svg>, so
# a non-greedy element match is sufficient and does not need an XML parser --
# which would also have to cope with the boards' `<x-dc>` and `<helmet>` custom
# elements and their unescaped `&mdash;`.
SVG_RE = re.compile(r"<svg\b[^>]*>.*?</svg>", re.DOTALL)
ATTR_RE = r'{}\s*=\s*"([^"]*)"'


def attr(markup, name):
    m = re.search(ATTR_RE.format(re.escape(name)), markup[: markup.index(">") + 1])
    return m.group(1) if m else None


def extract(name, spec, repo):
    """Locate one icon on its board and return (markup, w, h, viewbox).

    Fails the whole run rather than falling back to anything: an icon set that
    is quietly one icon short, or quietly holds a *different* icon, is exactly
    the class of bug this generator exists to make impossible.
    """
    board = repo / spec["source"]
    if not board.exists():
        sys.exit(f"error: {name}: board {spec['source']} does not exist")
    text = board.read_text()
    hits = [m for m in SVG_RE.finditer(text) if spec["match"] in m.group(0)]
    if not hits:
        sys.exit(
            f"error: {name}: no <svg> in {spec['source']} contains {spec['match']!r}.\n"
            f"  The board changed under this tool. Re-read it and update the match\n"
            f"  string in tools/iconc.py -- do not guess the geometry."
        )
    if len(hits) > 1:
        lines = ", ".join(str(text.count("\n", 0, m.start()) + 1) for m in hits)
        sys.exit(
            f"error: {name}: {len(hits)} <svg> elements in {spec['source']} contain "
            f"{spec['match']!r} (lines {lines}).\n"
            f"  A match must be unique or the generator would be picking one at random.\n"
            f"  Narrow it, or point `source` at a board where the mark appears once."
        )
    m = hits[0]
    markup = m.group(0)
    line = text.count("\n", 0, m.start()) + 1
    w, h, viewbox = attr(markup, "width"), attr(markup, "height"), attr(markup, "viewBox")
    for field, value in (("width", w), ("height", h), ("viewBox", viewbox)):
        if value is None:
            sys.exit(f"error: {name}: the <svg> at {spec['source']}:{line} has no {field}")
    try:
        w, h = int(round(float(w))), int(round(float(h)))
    except ValueError:
        sys.exit(f"error: {name}: {spec['source']}:{line} sizes it {w!r}x{h!r}, not in pixels")
    if w <= 0 or h <= 0:
        sys.exit(f"error: {name}: {spec['source']}:{line} sizes it {w}x{h}")
    # A mark that lives inside an inverted block is authored in white (the
    # board's CONTINUE arrow is), and white on the white ground below rasterises
    # to nothing. Colour is not part of an icon: the bitmap is coverage and
    # reader::Ink picks the colour at draw time. So an all-white mark is
    # re-coloured to black. Only an all-white one -- a mark that mixes black and
    # white is using white as a knockout, and flattening that would destroy it.
    body = markup[markup.index(">") + 1 :]
    inverted = "#ffffff" in body.lower() and "#000000" not in body.lower()
    if inverted:
        markup = re.sub("#ffffff", "#000000", markup, flags=re.IGNORECASE)
    return {"markup": markup, "size": (w, h), "viewbox": viewbox, "line": line,
            "inverted": inverted}

# Chrome will not open a window smaller than a platform minimum, and a
# screenshot of a clamped window is the wrong size. Render into a comfortably
# larger frame with the SVG pinned at the origin and crop, so the icon's own
# pixel grid is untouched by the frame.
PAD = 60


def rasterise(name, found, tmpdir):
    """Rasterise one icon to an (w, h) list-of-rows of 8-bit ink coverage.

    The board's `<svg>` goes in verbatim -- its own width, height, viewBox and
    `fill` attribute included. Re-authoring any of those here is what let this
    tool drift from the design in the first place.
    """
    w, h = found["size"]
    page = (
        '<!doctype html><meta charset="utf-8">'
        "<style>html,body{margin:0;padding:0;background:#fff}"
        "svg{position:absolute;left:0;top:0;display:block}</style>"
        f'{found["markup"]}'
    )
    html = tmpdir / f"{name}.html"
    html.write_text(page)
    png = tmpdir / f"{name}.png"
    subprocess.run(
        [CHROME, "--headless", "--disable-gpu", "--force-device-scale-factor=1",
         "--hide-scrollbars", "--default-background-color=FFFFFFFF",
         # Same reason as tools/compare-design.py: without a virtual-time budget
         # the screenshot can fire before the page has painted.
         "--virtual-time-budget=4000",
         f"--window-size={w + PAD},{h + PAD}", f"--screenshot={png}",
         html.as_uri()],
        check=True, capture_output=True)
    if not png.exists():
        sys.exit(f"error: Chrome produced no screenshot for {name}")
    im = Image.open(png).convert("L").crop((0, 0, w, h))
    px = im.load()
    # Ink, not light: a black stroke on white paper is coverage 255.
    cov = [[255 - px[x, y] for x in range(w)] for y in range(h)]
    # A blank raster means the markup drew nothing visible -- an unresolved
    # `currentColor`, a stroke the same colour as the ground, a geometry that
    # missed its viewBox. Emitting an empty icon would ship an invisible mark.
    if not any(any(row) for row in cov):
        sys.exit(f"error: {name}: rasterised to a blank {w}x{h} bitmap; markup drew nothing")
    return cov


def quantise(cov):
    """8-bit ink coverage -> 2-bit level, with fontc.py's rounding."""
    return [[(c * 3 + 127) // 255 for c in row] for row in cov]


def pack(levels, w):
    """2-bit levels -> bytes, MSB-first, four pixels per byte."""
    row_bytes = (w * 2 + 7) // 8
    out = bytearray(row_bytes * len(levels))
    for y, row in enumerate(levels):
        for x, level in enumerate(row):
            if level:
                out[y * row_bytes + x // 4] |= level << (6 - 2 * (x % 4))
    return bytes(out), row_bytes


def contact_sheet(rendered, path, zoom=6):
    """1:1 and zoomed strips of every icon, for eyeballing the set as a set."""
    cell_w = max(len(levels[0]) for levels in rendered.values()) + 8
    tiles = []
    for name, levels in rendered.items():
        h, w = len(levels), len(levels[0])
        im = Image.new("L", (w, h), 255)
        px = im.load()
        for y in range(h):
            for x in range(w):
                px[x, y] = (255, 170, 85, 0)[levels[y][x]]
        tiles.append((name, im))
    # Two rows: every icon at 1:1, then every icon at `zoom`x nearest-neighbour,
    # which is the only way to actually see where the intermediate greys land.
    row_h = max(im.height for _, im in tiles)
    zoom_w = sum(im.width * zoom + 8 for _, im in tiles)
    sheet = Image.new("L", (max(cell_w * len(tiles), zoom_w), row_h + 8 + row_h * zoom + 16), 255)
    x = 4
    for _, im in tiles:
        sheet.paste(im, (x, 4))
        x += cell_w
    x = 4
    for _, im in tiles:
        sheet.paste(im.resize((im.width * zoom, im.height * zoom), Image.NEAREST),
                    (x, row_h + 12))
        x += im.width * zoom + 8
    pathlib.Path(path).parent.mkdir(parents=True, exist_ok=True)
    sheet.save(path)
    return sheet.size


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True, help="C++ header to write")
    ap.add_argument("--sheet", help="also write a 1:1 + 6x contact sheet PNG here")
    args = ap.parse_args()

    if not pathlib.Path(CHROME).exists():
        sys.exit(f"error: Chrome not found at {CHROME}")

    # The repo root, so the tool works from any working directory: this file is
    # tools/iconc.py, so its parent's parent is the root the `source` paths are
    # relative to.
    repo = pathlib.Path(__file__).resolve().parent.parent

    found = {name: extract(name, spec, repo) for name, spec in ICONS.items()}

    rendered, blobs = {}, {}
    with tempfile.TemporaryDirectory() as tmp:
        tmp = pathlib.Path(tmp)
        for name in ICONS:
            levels = quantise(rasterise(name, found[name], tmp))
            rendered[name] = levels
            blobs[name] = pack(levels, found[name]["size"][0])

    lines = [
        "// Generated from the design boards' inline SVG by tools/iconc.py - do not edit.",
        "// Regenerate with: make icons",
        "//",
        "// Every size and every coordinate below was read out of the board named on",
        "// each icon at generation time. Nothing here, and nothing in iconc.py, is a",
        "// transcript of the design that could fall behind it.",
        "//",
        "// 2-bit ink coverage per pixel (0..3), packed MSB-first four pixels per",
        "// byte, exactly as .rfnt v2 glyph bitmaps are. Icon::coverage in",
        "// core/src/icons.cpp unpacks it; reader::Plane splits it into the panel's",
        "// two grey planes.",
        "#pragma once",
        "#include <cstdint>",
        "",
        "namespace reader::icons::data {",
    ]
    for name, spec in ICONS.items():
        f = found[name]
        w, h = f["size"]
        blob, row_bytes = blobs[name]
        sym = spec["symbol"]
        hist = [0, 0, 0, 0]
        for row in rendered[name]:
            for level in row:
                hist[level] += 1
        lines += [
            "",
            f"// {name}: {spec['note']}",
            f"// {spec['source']}:{f['line']}, viewBox \"{f['viewbox']}\", drawn {w}x{h}"
            + ("  (authored in white; re-coloured)" if f["inverted"] else ""),
            f"// coverage levels 0/1/2/3: {hist[0]}/{hist[1]}/{hist[2]}/{hist[3]} px",
            f"inline constexpr int {sym}W = {w};",
            f"inline constexpr int {sym}H = {h};",
            f"inline constexpr uint8_t {sym}Bits[] = {{",
        ]
        for y in range(h):
            row = blob[y * row_bytes:(y + 1) * row_bytes]
            lines.append("    " + " ".join(f"0x{b:02X}," for b in row))
        lines.append("};")
    lines += ["", "}  // namespace reader::icons::data", ""]

    out = pathlib.Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))

    total = 0
    for name, spec in ICONS.items():
        f = found[name]
        w, h = f["size"]
        blob, _ = blobs[name]
        total += len(blob)
        hist = [0, 0, 0, 0]
        for row in rendered[name]:
            for level in row:
                hist[level] += 1
        print(f"{name:8s} {w:2d}x{h:<2d} 2bpp {len(blob):4d} bytes  "
              f"levels 0/1/2/3 = {hist[0]}/{hist[1]}/{hist[2]}/{hist[3]}  "
              f"viewBox {f['viewbox']!r} <- {spec['source']}:{f['line']}")
    rel = os.path.relpath(out).replace(os.sep, "/")
    print(f"{rel}: {len(ICONS)} icons, {total} bytes of bitmap")
    if args.sheet:
        size = contact_sheet(rendered, args.sheet, zoom=6)
        print(f"{args.sheet}: contact sheet {size[0]}x{size[1]} (1:1 row, then 6x)")


if __name__ == "__main__":
    main()
