#!/usr/bin/env python3
"""Regenerates test/unit/deflate_fixtures.h.

The fixtures are chosen for the PATHS THROUGH reader/inflate_stream.h, not for
variety of content: the 16 KB chunk cap and the ring wrap, stored blocks, an
overlapping match, fixed Huffman tables, and several blocks in one stream.

Run from the repo root:  python3 tools/mkdeflate.py
"""
import os
import struct
import textwrap
import zlib


def raw(data, level=9, strategy=zlib.Z_DEFAULT_STRATEGY):
    """Raw DEFLATE with no zlib header, which is what a zip entry holds."""
    c = zlib.compressobj(level, zlib.DEFLATED, -15, 9, strategy)
    return c.compress(data) + c.flush()


def carr(name, b, note):
    body = ", ".join("0x%02x" % x for x in b)
    wrapped = "\n".join("    " + l for l in textwrap.wrap(body, 92))
    return "// %s\nconstexpr unsigned char %s[] = {\n%s\n};\n" % (note, name, wrapped)


def stored_blocks(segments):
    """Hand-assembled stored blocks: BFINAL+BTYPE=00, LEN, ~LEN, bytes.

    Hand-made because zlib caps a stored block at 65,535 bytes, so getting three
    from zlib would mean a 128 KB fixture for a path that needs 60 bytes.
    """
    out = bytearray()
    for i, s in enumerate(segments):
        out.append(1 if i == len(segments) - 1 else 0)
        out += struct.pack("<HH", len(s), len(s) ^ 0xFFFF)
        out += s
    return bytes(out)


def main():
    out = []

    big = b"The captain's word was law, and the law was thin. " * 4000
    z = raw(big)
    out.append(carr("kLongRun", z,
                    "%d bytes -> %d: 12x the 16KB chunk cap, so the ring wraps and several chunk\n"
                    "// boundaries are crossed. Tiny on disk because the data is compressible."
                    % (len(z), len(big))))
    out.append("constexpr size_t kLongRunOut = %d;\n" % len(big))

    segs = [b"First stored block. ", b"Second, still stored. ", b"Third and final. "]
    out.append(carr("kStored", stored_blocks(segs),
                    "THREE stored blocks, hand-assembled: BFINAL+BTYPE=00, then LEN and ~LEN, then\n"
                    "// the bytes. Hand-made because zlib caps a stored block at 65,535 bytes, so\n"
                    "// three from zlib would be a 128KB fixture for a path that needs 60 bytes."))
    out.append('constexpr const char* kStoredOut =\n    "%s";\n' % b"".join(segs).decode())

    ovl = b"a" + b"b" * 5000 + b"c" * 300
    z1 = raw(ovl)
    out.append(carr("kOverlap", z1,
                    "%d bytes -> %d. Long runs of one byte, which DEFLATE codes as distance 1 -- a\n"
                    "// match that reads what it is writing. A memcpy would produce garbage."
                    % (len(z1), len(ovl))))
    out.append("constexpr size_t kOverlapOut = %d;\n" % len(ovl))

    fx = b"Fixed tables, from RFC 1951 section 3.2.6, built rather than tabulated."
    z2 = raw(fx, strategy=zlib.Z_FIXED)
    out.append(carr("kFixed", z2,
                    "%d bytes -> %d, forced to FIXED Huffman tables." % (len(z2), len(fx))))
    out.append('constexpr const char* kFixedOut =\n    "%s";\n' % fx.decode())

    c = zlib.compressobj(9, zlib.DEFLATED, -15)
    parts = []
    for i in range(6):
        parts.append(c.compress(bytes([65 + i]) * 9000))
        parts.append(c.flush(zlib.Z_FULL_FLUSH))
    parts.append(c.flush())
    z3 = b"".join(parts)
    exp3 = b"".join(bytes([65 + i]) * 9000 for i in range(6))
    out.append(carr("kMultiBlock", z3,
                    "%d bytes -> %d across SIX blocks (Z_FULL_FLUSH between each), so the\n"
                    "// block-header path runs repeatedly mid-stream rather than once."
                    % (len(z3), len(exp3))))
    out.append("constexpr size_t kMultiBlockOut = %d;  // 6 runs of 9000\n" % len(exp3))

    hdr = """#pragma once
// RAW DEFLATE FIXTURES FOR THE STREAMING DECODER, generated by tools/mkdeflate.py
// so the test data and the decoder cannot disagree about the format.
//
// Chosen for the PATHS THROUGH THE DECODER rather than for variety of content: the
// chunk cap and the ring wrap, stored blocks, an overlapping match, fixed tables,
// and several blocks in one stream. Each is a branch a single small fixture never
// reaches. The malformed cases are built in the test itself, by corrupting these.
#include <cstddef>

namespace deflatefix {

"""
    path = os.path.join("test", "unit", "deflate_fixtures.h")
    with open(path, "w") as f:
        f.write(hdr + "\n".join(out) + "\n}  // namespace deflatefix\n")
    print("wrote %s (%d bytes)" % (path, os.path.getsize(path)))


if __name__ == "__main__":
    main()
