#pragma once
// --- A CARD-BACKED BOOK, BECAUSE AN IN-MEMORY ONE CANNOT ANSWER SOME QUESTIONS ---
//
// This lived in an anonymous namespace inside test_reader_restream.cpp until a second
// test file wanted it. Extracted rather than copied, on this project's own rule that
// the second copy is the extraction point -- and for the reason reader_fixture.h was
// extracted before it: a `CardReading` that drifted between two files would have two
// tests believing they set up the same screen.
//
// WHY A CARD IS SOMETIMES NECESSARY, in the words of the file it came from:
//
//   `ChapterReader::bytesRead()` reads the inflate source's own count, and the
//   in-memory constructor readerfix::Reading uses has no inflater -- so it
//   reports 0 forever. An invisibility assertion on `chapterBytesRead()` over that
//   fixture is `0 == 0`: it passes with the walk clobbering the field, which is how
//   this was found (a mutation that should have bitten and did not).
//
// ReaderScreen::relayout wants a card for a different reason and the same shape: its
// CARD path is the one the device takes -- openChapterAt then a walk to the block --
// and the in-memory constructor takes the other branch entirely. A relayout test over
// an in-memory chapter would exercise neither openChapterAt nor the failure return.
//
// So this builds a real EPUB in memory, with epub_builder.h -- which is where the
// zip assembly moved when test_book.cpp became its second caller. The reason it is a
// separate header rather than more of this one: that file wants a zip and nothing
// else, where this one drags in a ReaderScreen, a theme and a type ramp.
//
// Not added to test/unit/epub_fixtures.h, which is generated by tools/mkzip.py and
// shared: this is a hand-written fixture, and that header is a checked-in generated
// artefact.
#include <memory>
#include <string>

#include "doctest.h"
#include "epub_builder.h"
#include "fake_fs.h"
#include "ramp.h"
#include "reader_fixture.h"
#include "reader/book.h"
#include "reader/screen_reader.h"
#include "reader/settings.h"
#include "reader/theme_quiet.h"

namespace cardfix {

// The second spine entry's default text. Named rather than inlined because a caller
// that overrides it is making a point about spine entry 1, and the default is what it
// is being contrasted with.
inline const char* kDefaultCh2 = "<html><body><p>Two.</p></body></html>";

// `ch2` IS A PARAMETER SO A SPINE ENTRY CAN PAGINATE TO NOTHING. Three of a real
// book's 92 entries do -- a cover and two title pages, each an `<img>` and nothing
// document.h models -- and walkToChapter's answer is to SKIP them in whichever
// direction it was going. So an empty LAST entry is the only way to make a jump to an
// in-range spine entry fail, which is the one refusal that gets past goToPosition's
// bounds check and therefore the only one that can observe where the anchor is set.
inline std::string epubWith(const std::string& ch1, const std::string& ch2 = kDefaultCh2) {
  const std::string container =
      "<?xml version=\"1.0\"?>"
      "<container version=\"1.0\" "
      "xmlns=\"urn:oasis:names:tc:opendocument:xmlns:container\">"
      "<rootfiles><rootfile full-path=\"OEBPS/content.opf\" "
      "media-type=\"application/oebps-package+xml\"/></rootfiles></container>";
  const std::string opf =
      "<?xml version=\"1.0\"?>"
      "<package xmlns=\"http://www.idpf.org/2007/opf\" version=\"3.0\" "
      "unique-identifier=\"bookid\">"
      "<metadata xmlns:dc=\"http://purl.org/dc/elements/1.1/\">"
      "<dc:identifier id=\"bookid\">urn:uuid:0000-1111</dc:identifier>"
      "<dc:title>Middlemarch</dc:title><dc:creator>George Eliot</dc:creator>"
      "<dc:language>en</dc:language></metadata>"
      "<manifest>"
      "<item id=\"ch1\" href=\"ch1.xhtml\" media-type=\"application/xhtml+xml\"/>"
      "<item id=\"ch2\" href=\"ch2.xhtml\" media-type=\"application/xhtml+xml\"/>"
      "</manifest>"
      "<spine><itemref idref=\"ch1\"/><itemref idref=\"ch2\"/></spine></package>";
  return epubbuild::buildZip({
      {"mimetype", "application/epub+zip", false},
      {"META-INF/container.xml", container, true},
      {"OEBPS/content.opf", opf, true},
      {"OEBPS/ch1.xhtml", ch1, true},
      {"OEBPS/ch2.xhtml", ch2, true},
  });
}

// The card-backed equivalent of readerfix::Reading. Held together because a
// ScalableFont borrows its bytes and a ReaderScreen borrows the FileSystem.
struct CardReading {
  ramp::Ramp ramp;
  reader::QuietTheme theme;
  readerfix::Body body;
  reader::PageMetrics m;
  FakeFileSystem fs;
  reader::OpenedBook ob;
  std::unique_ptr<reader::ReaderScreen> scr;

  // `ppem` AND `margins` ARE THE TWO HALVES OF A TYPE CHANGE, and both are here
  // because PageMetrics carries only one of them: the column comes from the margin
  // and the line height comes from the FACE, which init() pins to one pixel size. A
  // fixture that took only the metrics could build the narrower column and not the
  // bigger type, which is half of what a press on the Size row does.
  //
  // `startAt` restores a saved position exactly as the shell does -- set BEFORE
  // setMetrics, because setMetrics is the landing. That is what lets a caller build
  // the REFERENCE screen for a re-layout: a book opened fresh at the new geometry,
  // landed on the block, which is by construction the page relayout() must produce.
  //
  // Every parameter is defaulted to what the first caller passed, so nothing that
  // predates them changed.
  explicit CardReading(const std::string& ch1, int ppem = reader::kBodyPpem,
                       int margins = reader::Settings{}.margins,
                       reader::Cursor startAt = reader::Cursor{},
                       const std::string& ch2 = kDefaultCh2)
      : body(ppem) {
    reader::Settings s;
    s.margins = margins;
    theme.readerMetrics(480, 800, ramp.fonts, body.face, s, m);
    REQUIRE(fs.writeAll("/books/b.epub", epubWith(ch1, ch2)));
    const char* why = "";
    REQUIRE_MESSAGE(reader::openBook(fs, "/books/b.epub", ob, &why), std::string(why));
    scr = std::make_unique<reader::ReaderScreen>(fs, ob, 0, &body.face);
    if (startAt != reader::Cursor{}) scr->restoreAt(startAt);
    scr->setMetrics(m);
  }
};

}  // namespace cardfix
