#pragma once
// --- A CARD-BACKED BOOK, BECAUSE AN IN-MEMORY ONE CANNOT ANSWER SOME QUESTIONS ---
//
// This lived in an anonymous namespace inside test_reader_restream.cpp until a second
// test file wanted it. Extracted rather than copied, on this project's own rule that
// the second copy is the extraction point -- and for the reason reader_fixture.h was
// extracted before it: a `CardReading` that drifted between two files would have two
// tests believing they set up the same screen.
//
// WHY A CARD IS SOMETIMES NECESSARY, in the words of the file it came from:
//
//   `ChapterReader::bytesRead()` is `inflated_ != nullptr ? inflater_.produced() : 0`,
//   and the in-memory constructor readerfix::Reading uses has no inflater -- so it
//   reports 0 forever. An invisibility assertion on `chapterBytesRead()` over that
//   fixture is `0 == 0`: it passes with the walk clobbering the field, which is how
//   this was found (a mutation that should have bitten and did not).
//
// ReaderScreen::relayout wants a card for a different reason and the same shape: its
// CARD path is the one the device takes -- openChapterAt then a walk to the block --
// and the in-memory constructor takes the other branch entirely. A relayout test over
// an in-memory chapter would exercise neither openChapterAt nor the failure return.
//
// So this builds a real EPUB in memory. The one thing that makes it cheap is that
// DEFLATE has a STORED BLOCK MODE -- BTYPE=00, a 5-byte header and the bytes -- so
// a valid method-8 entry needs no compressor, only a framer. The inflater takes the
// same path it takes for a real book (`inflate_stream.cpp` validates the NLEN
// complement, so a mis-framed block would fail loudly rather than silently).
//
// Not added to test/unit/epub_fixtures.h, which is generated by tools/mkzip.py and
// shared: this is a hand-written fixture, and that header is a checked-in generated
// artefact.
#include <cstdint>
#include <memory>
#include <string>
#include <vector>

#include "doctest.h"
#include "fake_fs.h"
#include "ramp.h"
#include "reader_fixture.h"
#include "reader/book.h"
#include "reader/screen_reader.h"
#include "reader/settings.h"
#include "reader/theme_quiet.h"

namespace cardfix {

inline void put16(std::string& s, uint16_t v) {
  s += static_cast<char>(v & 0xFF);
  s += static_cast<char>((v >> 8) & 0xFF);
}
inline void put32(std::string& s, uint32_t v) {
  for (int i = 0; i < 4; ++i) s += static_cast<char>((v >> (8 * i)) & 0xFF);
}

// Raw DEFLATE (no zlib wrapper -- the zip's csize/usize carry the framing) made
// entirely of stored blocks. Valid DEFLATE that any inflater must accept.
inline std::string storedDeflate(const std::string& data) {
  std::string out;
  size_t at = 0;
  do {
    const size_t n = data.size() - at > 65535 ? 65535 : data.size() - at;
    const bool last = at + n >= data.size();
    out += static_cast<char>(last ? 1 : 0);  // BFINAL, BTYPE=00, then byte-aligned
    put16(out, static_cast<uint16_t>(n));
    put16(out, static_cast<uint16_t>(~static_cast<uint16_t>(n)));
    out.append(data, at, n);
    at += n;
  } while (at < data.size());
  return out;
}

struct ZipEntry {
  std::string name;
  std::string data;
  bool deflate = true;
};

// zip.cpp trusts the CENTRAL directory and validates no CRC, so the field is zero.
inline std::string buildZip(const std::vector<ZipEntry>& entries) {
  std::string out, central;
  for (const ZipEntry& e : entries) {
    const std::string raw = e.deflate ? storedDeflate(e.data) : e.data;
    const uint32_t off = static_cast<uint32_t>(out.size());
    put32(out, 0x04034B50);
    put16(out, 20);
    put16(out, 0);
    put16(out, e.deflate ? 8 : 0);
    put16(out, 0);
    put16(out, 0);
    put32(out, 0);  // crc32 -- not validated, see above
    put32(out, static_cast<uint32_t>(raw.size()));
    put32(out, static_cast<uint32_t>(e.data.size()));
    put16(out, static_cast<uint16_t>(e.name.size()));
    put16(out, 0);
    out += e.name;
    out += raw;

    put32(central, 0x02014B50);
    put16(central, 20);
    put16(central, 20);
    put16(central, 0);
    put16(central, e.deflate ? 8 : 0);
    put16(central, 0);
    put16(central, 0);
    put32(central, 0);
    put32(central, static_cast<uint32_t>(raw.size()));
    put32(central, static_cast<uint32_t>(e.data.size()));
    put16(central, static_cast<uint16_t>(e.name.size()));
    put16(central, 0);
    put16(central, 0);
    put16(central, 0);
    put16(central, 0);
    put32(central, 0);
    put32(central, off);
    central += e.name;
  }
  const uint32_t cdOff = static_cast<uint32_t>(out.size());
  out += central;
  put32(out, 0x06054B50);
  put16(out, 0);
  put16(out, 0);
  put16(out, static_cast<uint16_t>(entries.size()));
  put16(out, static_cast<uint16_t>(entries.size()));
  put32(out, static_cast<uint32_t>(central.size()));
  put32(out, cdOff);
  put16(out, 0);
  return out;
}

// The second spine entry's default text. Named rather than inlined because a caller
// that overrides it is making a point about spine entry 1, and the default is what it
// is being contrasted with.
inline const char* kDefaultCh2 = "<html><body><p>Two.</p></body></html>";

// `ch2` IS A PARAMETER SO A SPINE ENTRY CAN PAGINATE TO NOTHING. Three of a real
// book's 92 entries do -- a cover and two title pages, each an `<img>` and nothing
// document.h models -- and walkToChapter's answer is to SKIP them in whichever
// direction it was going. So an empty LAST entry is the only way to make a jump to an
// in-range spine entry fail, which is the one refusal that gets past goToPosition's
// bounds check and therefore the only one that can observe where the anchor is set.
inline std::string epubWith(const std::string& ch1, const std::string& ch2 = kDefaultCh2) {
  const std::string container =
      "<?xml version=\"1.0\"?>"
      "<container version=\"1.0\" "
      "xmlns=\"urn:oasis:names:tc:opendocument:xmlns:container\">"
      "<rootfiles><rootfile full-path=\"OEBPS/content.opf\" "
      "media-type=\"application/oebps-package+xml\"/></rootfiles></container>";
  const std::string opf =
      "<?xml version=\"1.0\"?>"
      "<package xmlns=\"http://www.idpf.org/2007/opf\" version=\"3.0\" "
      "unique-identifier=\"bookid\">"
      "<metadata xmlns:dc=\"http://purl.org/dc/elements/1.1/\">"
      "<dc:identifier id=\"bookid\">urn:uuid:0000-1111</dc:identifier>"
      "<dc:title>Middlemarch</dc:title><dc:creator>George Eliot</dc:creator>"
      "<dc:language>en</dc:language></metadata>"
      "<manifest>"
      "<item id=\"ch1\" href=\"ch1.xhtml\" media-type=\"application/xhtml+xml\"/>"
      "<item id=\"ch2\" href=\"ch2.xhtml\" media-type=\"application/xhtml+xml\"/>"
      "</manifest>"
      "<spine><itemref idref=\"ch1\"/><itemref idref=\"ch2\"/></spine></package>";
  return buildZip({
      {"mimetype", "application/epub+zip", false},
      {"META-INF/container.xml", container, true},
      {"OEBPS/content.opf", opf, true},
      {"OEBPS/ch1.xhtml", ch1, true},
      {"OEBPS/ch2.xhtml", ch2, true},
  });
}

// The card-backed equivalent of readerfix::Reading. Held together because a
// ScalableFont borrows its bytes and a ReaderScreen borrows the FileSystem.
struct CardReading {
  ramp::Ramp ramp;
  reader::QuietTheme theme;
  readerfix::Body body;
  reader::PageMetrics m;
  FakeFileSystem fs;
  reader::OpenedBook ob;
  std::unique_ptr<reader::ReaderScreen> scr;

  // `ppem` AND `margins` ARE THE TWO HALVES OF A TYPE CHANGE, and both are here
  // because PageMetrics carries only one of them: the column comes from the margin
  // and the line height comes from the FACE, which init() pins to one pixel size. A
  // fixture that took only the metrics could build the narrower column and not the
  // bigger type, which is half of what a press on the Size row does.
  //
  // `startAt` restores a saved position exactly as the shell does -- set BEFORE
  // setMetrics, because setMetrics is the landing. That is what lets a caller build
  // the REFERENCE screen for a re-layout: a book opened fresh at the new geometry,
  // landed on the block, which is by construction the page relayout() must produce.
  //
  // Every parameter is defaulted to what the first caller passed, so nothing that
  // predates them changed.
  explicit CardReading(const std::string& ch1, int ppem = reader::kBodyPpem,
                       int margins = reader::Settings{}.margins,
                       reader::Cursor startAt = reader::Cursor{},
                       const std::string& ch2 = kDefaultCh2)
      : body(ppem) {
    reader::Settings s;
    s.margins = margins;
    theme.readerMetrics(480, 800, ramp.fonts, body.face, s, m);
    REQUIRE(fs.writeAll("/books/b.epub", epubWith(ch1, ch2)));
    const char* why = "";
    REQUIRE_MESSAGE(reader::openBook(fs, "/books/b.epub", ob, &why), std::string(why));
    scr = std::make_unique<reader::ReaderScreen>(fs, ob, 0, &body.face);
    if (startAt != reader::Cursor{}) scr->restoreAt(startAt);
    scr->setMetrics(m);
  }
};

}  // namespace cardfix
