#pragma once
// --- A REAL EPUB, ASSEMBLED IN MEMORY, FOR TESTS THAT NEED ONE SHAPED A PARTICULAR
// --- WAY.
//
// The zip half of this was cardfix::buildZip in card_book_fixture.h until a second
// caller wanted it, which is this project's own extraction point. It is here rather
// than there because card_book_fixture.h drags in ReaderScreen, a theme and a type
// ramp to build a CardReading, and test_book.cpp wants none of those -- it tests the
// layer that turns a file into offsets.
//
// NOT IN test/unit/epub_fixtures.h, and that decision is inherited rather than new:
// that header is GENERATED by tools/mkzip.py and says so at the top, so a
// hand-written fixture in it would be erased by the next regeneration. It also could
// not serve withCoverImage(), which takes its bytes at RUN time -- a generated
// constant array cannot.
//
// The one thing that makes assembling an EPUB here cheap is that DEFLATE has a
// STORED BLOCK MODE -- BFINAL/BTYPE=00, a 5-byte header and the bytes -- so a valid
// method-8 entry needs no compressor, only a framer. inflate_stream.cpp validates
// the NLEN complement, so a mis-framed block fails loudly rather than silently.
#include <cstdint>
#include <string>
#include <vector>

namespace epubbuild {

inline void put16(std::string& s, uint16_t v) {
  s += static_cast<char>(v & 0xFF);
  s += static_cast<char>((v >> 8) & 0xFF);
}
inline void put32(std::string& s, uint32_t v) {
  for (int i = 0; i < 4; ++i) s += static_cast<char>((v >> (8 * i)) & 0xFF);
}

// Raw DEFLATE (no zlib wrapper -- the zip's csize/usize carry the framing) made
// entirely of stored blocks. Valid DEFLATE that any inflater must accept.
inline std::string storedDeflate(const std::string& data) {
  std::string out;
  size_t at = 0;
  do {
    const size_t n = data.size() - at > 65535 ? 65535 : data.size() - at;
    const bool last = at + n >= data.size();
    out += static_cast<char>(last ? 1 : 0);  // BFINAL, BTYPE=00, then byte-aligned
    put16(out, static_cast<uint16_t>(n));
    put16(out, static_cast<uint16_t>(~static_cast<uint16_t>(n)));
    out.append(data, at, n);
    at += n;
  } while (at < data.size());
  return out;
}

struct ZipEntry {
  std::string name;
  std::string data;
  bool deflate = true;
};

// zip.cpp trusts the CENTRAL directory and validates no CRC, so the field is zero.
inline std::string buildZip(const std::vector<ZipEntry>& entries) {
  std::string out, central;
  for (const ZipEntry& e : entries) {
    const std::string raw = e.deflate ? storedDeflate(e.data) : e.data;
    const uint32_t off = static_cast<uint32_t>(out.size());
    put32(out, 0x04034B50);
    put16(out, 20);
    put16(out, 0);
    put16(out, e.deflate ? 8 : 0);
    put16(out, 0);
    put16(out, 0);
    put32(out, 0);  // crc32 -- not validated, see above
    put32(out, static_cast<uint32_t>(raw.size()));
    put32(out, static_cast<uint32_t>(e.data.size()));
    put16(out, static_cast<uint16_t>(e.name.size()));
    put16(out, 0);
    out += e.name;
    out += raw;

    put32(central, 0x02014B50);
    put16(central, 20);
    put16(central, 20);
    put16(central, 0);
    put16(central, e.deflate ? 8 : 0);
    put16(central, 0);
    put16(central, 0);
    put32(central, 0);
    put32(central, static_cast<uint32_t>(raw.size()));
    put32(central, static_cast<uint32_t>(e.data.size()));
    put16(central, static_cast<uint16_t>(e.name.size()));
    put16(central, 0);
    put16(central, 0);
    put16(central, 0);
    put16(central, 0);
    put32(central, 0);
    put32(central, off);
    central += e.name;
  }
  const uint32_t cdOff = static_cast<uint32_t>(out.size());
  out += central;
  put32(out, 0x06054B50);
  put16(out, 0);
  put16(out, 0);
  put16(out, static_cast<uint16_t>(entries.size()));
  put16(out, static_cast<uint16_t>(entries.size()));
  put32(out, static_cast<uint32_t>(central.size()));
  put32(out, cdOff);
  put16(out, 0);
  return out;
}

// --- COVER FIXTURES -----------------------------------------------------------
//
// Every cover book below is the SAME two-chapter book with one image added, so a
// difference between two of them is the OPF route and nothing else.
//
// THE COVER LIVES IN A SUBDIRECTORY (`OEBPS/images/cover.jpg`) ON PURPOSE. An OPF's
// href is relative to the OPF's own directory, so a cover at `OEBPS/cover.jpg` would
// resolve correctly even for an implementation that ignored the base entirely --
// which is the bug resolveHref exists to catch, and a fixture that cannot fail it is
// not testing it.
//
// AND IT IS STORED, method 0, as a real EPUB's JPEG is: an already-compressed image
// gains nothing from DEFLATE, and storing it here means `deflated == false` reaches
// the span rather than being a value no fixture ever produces.
inline const char* kCoverEntry = "OEBPS/images/cover.jpg";

// Not a JPEG. The fixtures that use it are about WHERE the cover is, and nothing on
// this path decodes it -- withCoverImage() is for a caller with real bytes.
inline const char* kFakeCoverBytes = "not really a jpeg, but bytes all the same";

namespace detail {

// `metaExtra` goes inside <metadata>, `itemExtra` inside <manifest>. Everything else
// is one book, so the fixtures differ only where they mean to.
inline std::string assemble(const std::string& metaExtra, const std::string& itemExtra,
                            const std::string& coverBytes, bool withCoverEntry) {
  const std::string container =
      "<?xml version=\"1.0\"?>"
      "<container version=\"1.0\" "
      "xmlns=\"urn:oasis:names:tc:opendocument:xmlns:container\">"
      "<rootfiles><rootfile full-path=\"OEBPS/content.opf\" "
      "media-type=\"application/oebps-package+xml\"/></rootfiles></container>";
  const std::string opf =
      "<?xml version=\"1.0\"?>"
      "<package xmlns=\"http://www.idpf.org/2007/opf\" version=\"3.0\" "
      "unique-identifier=\"bookid\">"
      "<metadata xmlns:dc=\"http://purl.org/dc/elements/1.1/\">"
      "<dc:identifier id=\"bookid\">urn:uuid:0000-1111</dc:identifier>"
      "<dc:title>Middlemarch</dc:title><dc:creator>George Eliot</dc:creator>"
      "<dc:language>en</dc:language>" +
      metaExtra +
      "</metadata>"
      "<manifest>"
      "<item id=\"ch1\" href=\"ch1.xhtml\" media-type=\"application/xhtml+xml\"/>"
      "<item id=\"ch2\" href=\"ch2.xhtml\" media-type=\"application/xhtml+xml\"/>" +
      itemExtra +
      "</manifest>"
      "<spine><itemref idref=\"ch1\"/><itemref idref=\"ch2\"/></spine></package>";

  std::vector<ZipEntry> entries = {
      {"mimetype", "application/epub+zip", false},
      {"META-INF/container.xml", container, true},
      {"OEBPS/content.opf", opf, true},
      {"OEBPS/ch1.xhtml", "<html><body><p>One.</p></body></html>", true},
      {"OEBPS/ch2.xhtml", "<html><body><p>Two.</p></body></html>", true},
  };
  if (withCoverEntry) entries.push_back({kCoverEntry, coverBytes, false});
  return buildZip(entries);
}

// The manifest item every cover route names. `props` is written out verbatim when
// non-empty, so a caller can state a whole space-separated list.
inline std::string coverItem(const std::string& props) {
  std::string s =
      "<item id=\"cover-img\" href=\"images/cover.jpg\" media-type=\"image/jpeg\"";
  if (!props.empty()) s += " properties=\"" + props + "\"";
  return s + "/>";
}

}  // namespace detail

// A book that declares no cover at all. 225 of 225 corpus books declare one, so this
// is not a shape found in the wild -- it is the shape the firmware must not refuse.
inline std::string minimalEpub() { return detail::assemble("", "", "", false); }

// ROUTE 1: `<meta name="cover" content="id">`, the EPUB 2 convention. Not in any
// spec, and overwhelmingly the one the corpus uses.
inline std::string withCoverMetaTag() {
  return detail::assemble("<meta name=\"cover\" content=\"cover-img\"/>",
                          detail::coverItem(""), kFakeCoverBytes, true);
}

// ROUTE 2: EPUB 3's `properties="cover-image"`. The list is deliberately TWO tokens
// with the interesting one SECOND -- `properties` is a space-separated set, so a
// fixture stating it alone cannot tell a token walk from a string compare.
inline std::string withCoverProperties() {
  return detail::assemble("", detail::coverItem("svg cover-image"), kFakeCoverBytes,
                          true);
}

// A book whose only `cover-image` is a SUBSTRING of some other property. This is the
// fixture that makes the token walk load-bearing: a `find()` matches it, and the book
// declares no cover at all.
inline std::string withCoverPropertiesLookalike() {
  return detail::assemble("", detail::coverItem("not-cover-image"), kFakeCoverBytes,
                          true);
}

// BOTH ROUTES, DISAGREEING. Real books carry this: `<meta name="cover">` pointing at
// the cover PAGE while `properties="cover-image"` sits on the image. Without a
// fixture where the two name different entries, "the manifest's declaration wins" is
// a claim in a comment that no test can reach.
//
// The decoy is a real archive entry and DEFLATED, where the image is stored -- so the
// storage method alone says which route won, and a wrong answer cannot hide behind
// an entry that happens to be missing.
inline std::string withBothCoverRoutesDisagreeing() {
  return detail::assemble(
      "<meta name=\"cover\" content=\"cover-page\"/>",
      "<item id=\"cover-page\" href=\"ch2.xhtml\" media-type=\"application/xhtml+xml\"/>" +
          detail::coverItem("cover-image"),
      kFakeCoverBytes, true);
}

// A manifest that DECLARES a cover the archive does not hold. Every other fixture
// here has both halves, so without this the "a missing cover entry is not a refusal"
// clause in book.cpp is a claim no test can reach -- a mutation making it a refusal
// failed nothing, which is what put this fixture here.
inline std::string withCoverDeclaredButAbsent() {
  return detail::assemble("<meta name=\"cover\" content=\"cover-img\"/>",
                          detail::coverItem(""), "", false);
}

// `<meta name="cover">` naming an id no manifest item carries. Real OPFs get this
// wrong the same way they get `unique-identifier` wrong, and the same call applies:
// a cross-reference inside the OPF that does not resolve costs the book the thing it
// named and nothing else.
inline std::string withCoverIdUnresolved() {
  return detail::assemble("<meta name=\"cover\" content=\"no-such-item\"/>", "", "",
                          false);
}

// The same book carrying REAL image bytes, stored, declared the EPUB 2 way. For a
// caller that is going to decode what comes back.
inline std::string withCoverImage(const std::string& bytes) {
  return detail::assemble("<meta name=\"cover\" content=\"cover-img\"/>",
                          detail::coverItem(""), bytes, true);
}

}  // namespace epubbuild
