// The page shell: load the manifest, decide whether this browser may flash at
// all, fill the band, and drive the states.
//
// The serial work is in reader.js and it READS ONLY. Nothing on this page
// writes to a device yet, which is why the check can be run on a reader that
// somebody depends on.

'use strict';

import { requestReader, identify, install } from './reader.js';

/** Where the page's facts come from. Generated by tools/webmanifest.py. */
const MANIFEST_URL = 'manifest.json';

/**
 * Why this browser cannot flash, or null if it can.
 *
 * THE MOBILE RULE IS COMPLETE BY CONSTRUCTION, NOT BY LUCK, and it is worth
 * saying why, because the obvious version of it is not:
 *
 *   The only mobile browser with Web Serial is Chrome on Android 148+. Every
 *   browser on iOS is WebKit, which has no Web Serial and is not getting it;
 *   Firefox for Android has none either. So `navigator.serial` alone already
 *   refuses every mobile browser but one.
 *
 *   That one is Chromium, and `navigator.userAgentData` is a Chromium API. So
 *   the single case the capability check misses is exactly the case where
 *   `userAgentData.mobile` is available to catch it. The two checks together
 *   have no gap: a browser that has Web Serial and no `userAgentData` cannot be
 *   mobile, because no such browser exists.
 *
 * That is why this does not sniff a user-agent string. If Safari or Firefox
 * ever ship Web Serial on a phone, this rule stops being complete and the
 * comment above is the thing to come back to.
 */
function refusalReason() {
  if (navigator.userAgentData && navigator.userAgentData.mobile === true) {
    return 'mobile';
  }
  if (!('serial' in navigator)) {
    return 'browser';
  }
  return null;
}

/** Fetch the manifest, or throw with something a person can act on. */
async function loadManifest() {
  let response;
  try {
    response = await fetch(MANIFEST_URL, { cache: 'no-cache' });
  } catch (cause) {
    throw new Error('The page could not reach its own manifest.', { cause });
  }
  if (!response.ok) {
    throw new Error('The page could not read its own manifest (' + response.status + ').');
  }
  return response.json();
}

/**
 * Fill the band's right-hand slot.
 *
 * It names the version being OFFERED, which is the release the deploy fetched,
 * and falls back to the version this tree expects when no release is attached
 * -- which is what a local checkout sees, since only the Pages workflow runs
 * the generator with --tag.
 */
function fillBand(manifest) {
  const meta = document.querySelector('[data-band-meta]');
  if (!meta) return;
  const version = manifest.firmware ? manifest.firmware.version : manifest.expects;
  // Only the version. The models are markup beside it, so CSS can drop them on
  // a narrow window without this function having to know the width.
  meta.textContent = 'V ' + version;
}

/** Show exactly one of the page's top-level states. */
function show(name) {
  for (const section of document.querySelectorAll('[data-state-view]')) {
    section.hidden = section.dataset.stateView !== name;
  }
}

/** Set a rail step's marker: pending, active, done or failed. */
function setStep(step, state) {
  for (const row of document.querySelectorAll('[data-step="' + step + '"]')) {
    row.dataset.state = state;
  }
}

function setSteps(map) {
  for (const [step, state] of Object.entries(map)) setStep(step, state);
}

/** Write a value into every slot that asks for it by name. */
function setFact(name, value) {
  for (const cell of document.querySelectorAll('[data-fact="' + name + '"]')) {
    cell.textContent = value;
  }
}

/**
 * Connect to a reader, say what it is, and compare its layout.
 *
 * WRITES NOTHING. The install itself is not built, so this ends by reporting
 * what it found -- which is useful on its own: the one open question about this
 * device family is whether an X4's partition table matches the X3's, and this
 * is what can answer it.
 */
// THE SESSION OUTLIVES THE CHECK, because the install reuses the open loader
// rather than resetting the chip a second time. That means something has to
// close it when the install never happens: a reader whose port is still held
// cannot be picked again, and the only way out would be reloading the page.
let openSession = null;

async function closeOpenSession() {
  const session = openSession;
  openSession = null;
  if (session) await session.close().catch(() => {});
}

async function connectAndCheck(manifest) {
  await closeOpenSession();
  let port;
  try {
    port = await requestReader();
  } catch (error) {
    // The picker was dismissed, or no port was chosen. Not a failure state:
    // nothing was attempted, so the page stays where it was.
    return;
  }

  show('connecting');
  setSteps({ connect: 'done', check: 'active', write: 'pending', start: 'pending' });
  setFact('chip', 'reading…');
  setFact('flash', '—');
  setFact('layout', '—');

  let session = null;
  try {
    session = await identify(port, manifest, (stage) => {
      if (stage === 'reading-table') setFact('layout', 'READING…');
    });

    openSession = session;
    setFact('chip', session.chip);
    setFact('flash', session.flashSize ? session.flashSize.replace('MB', ' MB') : 'UNKNOWN');
    setFact('layout', session.layout.matches ? 'AS EXPECTED' : 'DIFFERENT');

    const matches = session.layout.matches;
    setSteps({ connect: 'done', check: 'done', write: 'pending', start: 'pending' });
    show('checked');
    setFact('result-chip', session.chip);
    setFact('result-flash', session.flashSize ? session.flashSize.replace('MB', ' MB') : 'UNKNOWN');
    setFact('result-layout', matches ? 'AS EXPECTED' : 'DIFFERENT');

    // The board specimens the matching case. These four carry the other one,
    // and they are set together so a mismatch cannot end up wearing half of a
    // match's wording.
    const title = document.querySelector('[data-verdict-title]');
    const verdict = document.querySelector('[data-verdict]');
    const detail = document.querySelector('[data-verdict-detail]');
    const targetLabel = document.querySelector('[data-verdict-target-label]');
    if (title) {
      title.textContent = matches ? 'THE LAYOUT MATCHES' : 'THIS READER IS LAID OUT DIFFERENTLY';
    }
    if (verdict) {
      verdict.textContent = matches
        ? 'The reader has the layout Encre expects. Encre goes into slot '
          + session.install.slot + ', and the firmware it came with stays where it is.'
        : 'Encre expects a different set of partitions on this reader. Installing would have to '
          + 'replace everything on it, including the firmware it came with.';
    }
    if (targetLabel) targetLabel.textContent = matches ? 'WRITES TO' : 'DIFFERENCES';

    // THE INSTALL IS OFFERED ONLY WHERE IT EXISTS. On a reader laid out
    // differently, installing means replacing everything on it, and the backup
    // that makes that survivable is not built. A button that would start the
    // destructive path is worse than no button, so the state says so instead.
    const installButton = document.querySelector('[data-install]');
    const noInstall = document.querySelector('[data-no-install]');
    if (installButton) installButton.hidden = !matches;
    if (noInstall) noInstall.hidden = matches;
    if (installButton && matches) {
      installButton.onclick = () => runInstall(session, manifest, installButton);
    }
    // "SLOT 2" rather than "APP1": the boards' vocabulary, and the number is
    // counted in the manifest rather than mapped here.
    setFact('result-target', matches
      ? 'SLOT ' + session.install.slot
      : String(session.layout.differences.length));
    if (detail) {
      detail.textContent = matches
        ? 'Nothing has been written to the reader.'
        : session.layout.differences.join('. ') + '.';
    }
  } catch (error) {
    setSteps({ connect: 'done', check: 'failed', write: 'pending', start: 'pending' });
    show('failed');
    const slot = document.querySelector('[data-failure-detail]');
    if (slot) slot.textContent = error.message;
    openSession = null;
    if (session) await session.close().catch(() => {});
  }
}

/**
 * Write Encre, then tell the reader to start it.
 *
 * The session stays open from the check, so the chip is not reset a second time
 * and the port is never reopened.
 */
async function runInstall(session, manifest, button) {
  button.disabled = true;
  show('writing');
  setSteps({ connect: 'done', check: 'done', write: 'active', start: 'pending' });
  setFact('write-version', 'V ' + manifest.firmware.version);
  setFact('write-target', 'SLOT ' + manifest.layout.install.slot);
  setFact('write-keeps', manifest.layout.keeps.map((name, i) => 'SLOT ' + (i + 1)).join(', '));

  const bar = document.querySelector('[data-progress-bar]');
  const text = document.querySelector('[data-progress-text]');
  const percent = document.querySelector('[data-progress-percent]');
  const mb = (n) => (n / 1048576).toFixed(1) + ' MB';

  try {
    const result = await install(session, manifest, ({ stage, written, total }) => {
      const share = total ? Math.round((written / total) * 100) : 0;
      if (bar) bar.style.width = share + '%';
      if (percent) percent.textContent = share + '%';
      if (text) {
        text.textContent = stage === 'fetching' ? 'DOWNLOADING ENCRE'
          : stage === 'selecting' ? 'CHOOSING WHICH FIRMWARE TO START'
          : mb(written) + ' OF ' + mb(total);
      }
    });
    setSteps({ connect: 'done', check: 'done', write: 'done', start: 'active' });
    setFact('done-version', 'V ' + manifest.firmware.version);
    setFact('done-target', 'SLOT ' + result.slot);
    show('done');
  } catch (error) {
    setSteps({ connect: 'done', check: 'done', write: 'failed', start: 'pending' });
    show('failed');
    const slot = document.querySelector('[data-failure-detail]');
    if (slot) slot.textContent = error.message;
  } finally {
    openSession = null;
    await session.close().catch(() => {});
  }
}

async function main() {
  const refusal = refusalReason();
  let manifest = null;
  try {
    manifest = await loadManifest();
    fillBand(manifest);
  } catch (error) {
    // A missing manifest is not the reader's problem to solve, but it must not
    // look like a working page either.
    show('broken');
    const slot = document.querySelector('[data-broken-detail]');
    if (slot) slot.textContent = error.message;
    return;
  }

  if (refusal) {
    // The gate is on the document so CSS can key on it. The phone view drops
    // the tabs; a narrow desktop window must not.
    document.body.dataset.gate = refusal === 'mobile' ? 'phone' : 'unsupported';
    show(refusal === 'mobile' ? 'phone' : 'unsupported');
    return;
  }

  // Recovery has no `nobuild` view and wants none: it reads and writes a
  // reader that is already in front of it, so whether a release is attached is
  // none of its business. Asking the page whether it HAS the state is what
  // keeps that from being a list of page names in here.
  if (!manifest.firmware && document.querySelector('[data-state-view="nobuild"]')) {
    // The layout-only manifest a local checkout carries. The Pages deploy
    // always attaches a release, so this is a developer's view rather than
    // anything a reader meets.
    show('nobuild');
    return;
  }

  const connect = document.querySelector('[data-connect]');
  if (connect) {
    connect.disabled = false;
    connect.addEventListener('click', () => {
      connect.disabled = true;
      connectAndCheck(manifest).finally(() => { connect.disabled = false; });
    });
  }
  for (const again of document.querySelectorAll('[data-again]')) {
    again.addEventListener('click', async () => {
      await closeOpenSession();
      setSteps({ connect: 'pending', check: 'pending', write: 'pending', start: 'pending' });
      show('idle');
    });
  }

  show('idle');
}

// A module is deferred, so DOMContentLoaded may already have fired by the time
// this runs. Waiting for an event that has been and gone would leave the page
// blank with every state hidden.
if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', main);
} else {
  main();
}
