// Shared by the flasher and Recovery: load the manifest, decide whether this
// browser may flash at all, and fill the band.
//
// NO SERIAL CODE LIVES HERE YET. This is the deploy path and the gate; the
// esptool-js work (read the partition table at 0x8000, write the install slot,
// flip otadata) lands next, behind `startInstall` below.

'use strict';

/** Where the page's facts come from. Generated by tools/webmanifest.py. */
const MANIFEST_URL = 'manifest.json';

/**
 * Why this browser cannot flash, or null if it can.
 *
 * THE MOBILE RULE IS COMPLETE BY CONSTRUCTION, NOT BY LUCK, and it is worth
 * saying why, because the obvious version of it is not:
 *
 *   The only mobile browser with Web Serial is Chrome on Android 148+. Every
 *   browser on iOS is WebKit, which has no Web Serial and is not getting it;
 *   Firefox for Android has none either. So `navigator.serial` alone already
 *   refuses every mobile browser but one.
 *
 *   That one is Chromium, and `navigator.userAgentData` is a Chromium API. So
 *   the single case the capability check misses is exactly the case where
 *   `userAgentData.mobile` is available to catch it. The two checks together
 *   have no gap: a browser that has Web Serial and no `userAgentData` cannot be
 *   mobile, because no such browser exists.
 *
 * That is why this does not sniff a user-agent string. If Safari or Firefox
 * ever ship Web Serial on a phone, this rule stops being complete and the
 * comment above is the thing to come back to.
 */
function refusalReason() {
  if (navigator.userAgentData && navigator.userAgentData.mobile === true) {
    return 'mobile';
  }
  if (!('serial' in navigator)) {
    return 'browser';
  }
  return null;
}

/** Fetch the manifest, or throw with something a person can act on. */
async function loadManifest() {
  let response;
  try {
    response = await fetch(MANIFEST_URL, { cache: 'no-cache' });
  } catch (cause) {
    throw new Error('The page could not reach its own manifest.', { cause });
  }
  if (!response.ok) {
    throw new Error('The page could not read its own manifest (' + response.status + ').');
  }
  return response.json();
}

/**
 * Fill the band's right-hand slot.
 *
 * It names the version being OFFERED, which is the release the deploy fetched,
 * and falls back to the version this tree expects when no release is attached
 * -- which is what a local checkout sees, since only the Pages workflow runs
 * the generator with --tag.
 */
function fillBand(manifest) {
  const meta = document.querySelector('[data-band-meta]');
  if (!meta) return;
  const version = manifest.firmware ? manifest.firmware.version : manifest.expects;
    // Only the version. The models are markup beside it, so CSS can drop them
  // on a narrow window without this function having to know the width.
  meta.textContent = 'V ' + version;
}

/** Show exactly one of the page's top-level states. */
function show(name) {
  for (const section of document.querySelectorAll('[data-state-view]')) {
    section.hidden = section.dataset.stateView !== name;
  }
}

/**
 * The install entry point, and it is deliberately inert.
 *
 * Wiring a button to nothing would be worse than leaving it disabled: the
 * reader would press it, see no change, and have no way to tell a dead page
 * from a reader that did not answer. So until the esptool-js work lands, the
 * slab says so and stays disabled.
 */
function startInstall() {
  throw new Error('not built yet');
}

async function main() {
  const refusal = refusalReason();
  let manifest = null;
  try {
    manifest = await loadManifest();
    fillBand(manifest);
  } catch (error) {
    // A missing manifest is not the reader's problem to solve, but it must not
    // look like a working page either.
    show('broken');
    const slot = document.querySelector('[data-broken-detail]');
    if (slot) slot.textContent = error.message;
    return;
  }

  if (refusal) {
    // The gate is on the document so CSS can key on it. The phone view drops
    // the tabs; a narrow desktop window must not.
    document.body.dataset.gate = refusal === 'mobile' ? 'phone' : 'unsupported';
    show(refusal === 'mobile' ? 'phone' : 'unsupported');
    return;
  }

  // Recovery has no `nobuild` view and wants none: it reads and writes a
  // reader that is already in front of it, so whether a release is attached is
  // none of its business. Asking the page whether it HAS the state is what
  // keeps that from being a list of page names in here.
  if (!manifest.firmware && document.querySelector('[data-state-view="nobuild"]')) {
    // The layout-only manifest a local checkout carries. The Pages deploy
    // always attaches a release, so this is a developer's view rather than
    // anything a reader meets.
    show('nobuild');
    return;
  }

  show('idle');
}

document.addEventListener('DOMContentLoaded', main);
